### ISSUE TITLE
[Bug]: Crash when opening inventory

### ISSUE THREAD

**Issue by cal1407** [cech12/ExtendedMushrooms#87] opened 2024-05-23 16:42 UTC
### Minecraft Version

1.20.1

### Forge Version

47.2.30

### Mod Version

4.1.2.0

### Describe the Issue

The game would randomly crash when opening the inventory, with the crash report pinpointing to this mod.

### Logs

https://pastebin.com/7xnBuyCQ

**Comment by cech12** [comment] 2024-05-23 17:26
Thanks for your report! It seems to be a compatibility issue with the Sawmill mod. I opened an issue there to fix crashing the game: https://github.com/MehVahdJukaar/sawmill/issues/43
The compatibility issue with Sawmill/Moonlight will be fixed (hopefully) when I have time. :)

Related issue: #82

**Comment by cech12** [comment] 2024-05-24 13:10
Unfortunately I could not reproduce your issue. 
I found a possible root of your crash and the upcoming release 1.20.1-4.1.3.1 contains a fix, that hopefully fixes your issue.
Please test it and let me know, if the game is still crashing in your environment.

**Comment by cal1407** [comment] 2024-05-25 10:40
Hi, the game would still crash from time to time, but I do notice that the frequency of the crash is much rarer compared to the previous versions

**Comment by cech12** [comment] 2024-05-25 11:12
That is really weird. Are you playing a mod pack or is that an own collection of mods? Could you add some more of your crash logs?

**Comment by cal1407** [comment] 2024-05-25 11:38
Here you go.

Crash log: https://pastebin.com/WN4tqrsP
Truncated log: https://pastebin.com/dGWNiu1b

**Comment by cech12** [comment] 2024-05-25 15:54
Are you using Forge and Fabric mods together? How is that possible?^^ Maybe there is a mod that changes the item & block registry in such a way that this issue arises.

**Comment by cal1407** [comment] 2024-05-26 03:09
I do use [Sinytra's Connector](https://modrinth.com/mod/connector), which allows Fabric mods to run on Forge. Maybe that's the cause of the crash?

**Comment by cech12** [comment] 2024-05-26 05:27
Maybe :) Could you try removing it and test if the crash is still there without it and the fabric mods?

**Comment by cech12** [comment] 2024-05-29 05:39
@cal1407 Could you test it already? :)

**Comment by cal1407** [comment] 2024-05-29 09:24
Sorry for the delayed response. Actually, my game has not crashed again, even though I still have Connector installed. So, I think you can close the issue for now.

**Comment by cal1407** [comment] 2024-05-29 10:17
Sorry for the delay. Was gonna tell you that the crash is gone but ironically it happened again just now not long after you messaged me. 

So I tried removing most of my mods except for sawmill, extended mushroom and connectors and the game worked just fine. Next I tried loading all the fabric mods I have along with extended mushroom and sawmill and it also worked just fine. To conclude, I think it unlikely that connectors and/or other fabric mods are the culprit.

**Comment by cech12** [comment] 2024-05-29 11:34
It would be great if you could try to find out which of your used mods is causing these crashes. You could try to force the crash when you open the villager trades for the sawmill job in jei. (as I could expect from all I can see in your craah logs)

**Comment by cal1407** [comment] 2024-05-30 11:01
I tried loading my Fabric mods one by one, but I am unable to reproduce the crash. You can just close the rep since the crash does not happen that often anyway.

**Comment by cech12** [comment] 2024-05-30 17:03
Ok I will close this issue. If you have another issue please feel free to open a new issue here. Thanks for your report :)

**Closed as not planned** 2024-05-30 17:03 UTC
Labels: bug, information needed, wontfix, mod support

**Comment by cech12** [comment] 2024-06-06 05:56
@cal1407 Last week a new version (1.20-1.4.1) of Sawmill was released and the error details were extended. When you install it and post another crashlog when the crash arises, we could see more. :)
