### ISSUE TITLE
[Bug]: Server crash while creating nether wart using fairy ring

### ISSUE THREAD

**Issue by RattenDieb** [cech12/ExtendedMushrooms#90] opened 2024-11-18 17:16 UTC
### Minecraft Version

1.20.1

### Forge Version

47.3.11

### Mod Version

1.20.1.-4.1.3.2

### Modpack or other Mod

Modpack: https://www.curseforge.com/minecraft/modpacks/rattenland

### Describe the Issue

- Build Fairy Ring
- Thrown Berrys to ring, to get nether wart
- got this error on server (hosted) 

Caused by: java.lang.NullPointerException: Cannot invoke "cech12.extendedmushrooms.api.recipe.FairyRingRecipe.getResultItemStack()" because "entity.currentRecipe" is null
	at cech12.extendedmushrooms.blockentity.FairyRingBlockEntity.tick(FairyRingBlockEntity.java:367) ~[extendedmushrooms-1.20.1-4.1.3.2.jar%23283!/:1.20.1-4.1.3.2]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689) ~[server-1.20.1-20230612.114412-srg.jar%23373!/:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) ~[server-1.20.1-20230612.114412-srg.jar%23373!/:?]
	at net.minecraft.world.level.Level.m_46463_(Level.java:468) ~[server-1.20.1-20230612.114412-srg.jar%23373!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[server-1.20.1-20230612.114412-srg.jar%23373!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23373!/:?]
	... 5 more

**Comment by cech12** [comment] 2024-11-18 18:49
Thanks for your report! I will look into that when I have time. :)

**Comment by cech12** [comment] 2024-11-19 19:03
The issue is fixed in the upcoming release 1.20.1-4.1.3.3. Thanks again for the report!

**Closed as completed by cech12** 2024-11-19 19:03 UTC
Labels: bug
