### ISSUE TITLE
[Bug]: Compatibility issue with Every Compat/Moonlight Lib

### ISSUE THREAD

**Issue by Zartrix** [cech12/ExtendedMushrooms#81] opened 2023-10-31 14:49 UTC
### Minecraft Version

1.20.1

### Forge Version

47.2.0

### Mod Version

4.1.0.0

### Modpack or other Mod

[Every Compat](https://modrinth.com/mod/every-compat) 2.6.15
[Another Furniture](https://modrinth.com/mod/another-furniture) 3.0.1
[Moonlight Lib](https://modrinth.com/mod/moonlight) 2.8.54
Optionally, any other mod that adds wood sets/logs/stems for comparison

Also, optionally, mods that provide more variants for wood. Above-mentioned are enough to see the issue though.
Chipped (+Athena and Resourceful Lib)
Supplementaries (+Supplementaries Squared)
Farmers Delight
Create
Woodster

### Describe the Issue

None of the Extended Mushroom wood/plank types have Furniture (or when other mods installed, cabinets, doors, bookshelves etc.) generated by Every Compat.
1. Start the game with mentioned mods
2. Join or create any creative world
3. Check the "Every Compat" tab on the second page (not available when only having the 3 linked mods and Extended Mushrooms)
4. There are no variants for Extended Mushroom wood/stem/plank types

If this issue is not on your side I'll gladly report this at Every Compat or Moonlight

### Logs

https://mclo.gs/vvfzeOM

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No performance-enhancing mods are being used

**Comment by cech12** [comment] 2023-10-31 15:24
Thanks for your report. I will look into thar, when I have time! :)

**Comment by cech12** [comment] 2023-10-31 17:33
I tried to fix the issue, but it seems to be a timing issue in the registring phase. I opened an issue at Moonlight repository to get help about that.

**Comment by cech12** [comment] 2023-11-04 07:10
I could fix the issue with the information of MehVahdJukaar! @Zartrix Thanks for your report. The issue is fixed in the upcoming version 1.20.1-4.1.0.1.

**Closed as completed by cech12** 2023-11-04 07:10 UTC
Labels: mod support
