### ISSUE TITLE
[Bug]: Server Occasionally Fails to start

### ISSUE THREAD

**Issue by Tyrius1** [cech12/ExtendedMushrooms#65] opened 2022-10-22 01:34 UTC
### Minecraft Version

1.19.2

### Forge Version

43.1.43

### Mod Version

1.19.2-3.0.1.1

### Modpack or other Mod

Custom modpack currently not released

### Describe the Issue

Server fail to start

### Logs

https://pastebin.com/UijMg5iG

### Do you use any performance-enhancing mods (e.g. OptiFine)?

I'm using quite a few performance mods.

**Comment by cech12** [comment] 2022-10-22 05:25
Thanks for ypur report, I will look into this, when I have time :)

**Comment by cech12** [comment] 2022-10-22 06:41
I could not reproduce the error but hopefully I found the source of this issue. It should be fixed in the upcoming versions 1.16.5-1.7.0.5, 1.18.2-2.0.1.1 and 1.19.2-3.0.1.2.
If it is not fixed, please let me know :)

**Closed as completed by cech12** 2022-10-22 06:41 UTC
Labels: bug
